name: remove_unused_localizations
description: "A Flutter package to clean unused localization keys from .arb files."
version: 0.0.2
homepage: https://github.com/OsamaAssaf/remove_unused_localizations
repository: https://github.com/OsamaAssaf/remove_unused_localizations
issue_tracker: https://github.com/OsamaAssaf/remove_unused_localizations/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
